### ISSUE TITLE
SKOSplay on Tomcat 404 problems

### ISSUE THREAD

**Issue by scuffster** [sparna-git/skos-play#71]
Hi, I've followed the instructions here https://github.com/sparna-git/skos-play/wiki/HowTo-SKOSPlayOnTomcat on deploying to Tomcat. 

1. I've installed Tomcat, and it works fine with the example apps that are part of the distribution
![Screenshot 2022-05-30 at 17 42 58](https://user-images.githubusercontent.com/237091/171033716-ad0be6a1-b3f4-463d-9bea-4e3d4f7091f6.png)
2. I've copied the [skos-play-0.9.1.war](https://github.com/sparna-git/skos-play/releases/download/0.9.1/skos-play-0.9.1.war)  war file to the webapps directory. and renamed it to skos-play.war
3. stopped and started tomcat
4. The skos-play directory is there
5. `drwxr-x---  3 tomcat tomcat      223 May 30 13:58 ROOT
drwxr-x--- 15 tomcat tomcat     4096 May 30 13:58 docs
drwxr-x---  7 tomcat tomcat       99 May 30 13:58 examples
drwxr-x---  6 tomcat tomcat       79 May 30 13:58 host-manager
drwxr-x---  6 tomcat tomcat      114 May 30 13:58 manager
-rw-r--r--  1 tomcat tomcat 79442251 May 30 15:22 skos-play.war
drwxr-x--- 12 tomcat tomcat      201 May 30 16:08 skos-play`

when I go to the tomcat server URL  I get a 404 "The requested resource [/skos-play/] is not available"
![Screenshot 2022-05-30 at 17 44 50](https://user-images.githubusercontent.com/237091/171033884-dae0f4b0-4daa-4515-8342-31f9ae22b05e.png)

I don't see anything in the wiki about adjusting privileges or access. - might that be the cause?

**Comment by tfrancart** [comment]
The application was not deployed properly.
You need to look in the log file of Tomcat to find a potential error message. Look in <tomcat>/logs/catalina.out, look for [ERROR] messages and let me know.

**Comment by scuffster** [comment]
Natalia.out content

`31-May-2022 08:33:24.723 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dorg.apache.catalina.security.SecurityListener.UMASK=0027
31-May-2022 08:33:24.723 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dignore.endorsed.dirs=
31-May-2022 08:33:24.723 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dcatalina.base=/opt/tomcat
31-May-2022 08:33:24.723 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dcatalina.home=/opt/tomcat
31-May-2022 08:33:24.723 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.io.tmpdir=/opt/tomcat/temp
31-May-2022 08:33:24.725 INFO [main] org.apache.catalina.core.AprLifecycleListener.lifecycleEvent The Apache Tomcat Native library which allows using OpenSSL was not found on the java.library.path: [/usr/java/packages/lib/amd64:/usr/lib64:/lib64:/lib:/usr/lib]
31-May-2022 08:33:25.146 INFO [main] org.apache.coyote.AbstractProtocol.init Initializing ProtocolHandler ["http-nio-8085"]
31-May-2022 08:33:25.190 INFO [main] org.apache.catalina.startup.Catalina.load Server initialization in [678] milliseconds
31-May-2022 08:33:25.234 INFO [main] org.apache.catalina.core.StandardService.startInternal Starting service [Catalina]
31-May-2022 08:33:25.235 INFO [main] org.apache.catalina.core.StandardEngine.startInternal Starting Servlet engine: [Apache Tomcat/10.0.21]
31-May-2022 08:33:25.260 INFO [main] org.apache.catalina.startup.HostConfig.deployWAR Deploying web application archive [/opt/tomcat/webapps/skos-play.war]
31-May-2022 08:33:31.306 INFO [main] org.apache.jasper.servlet.TldScanner.scanJars At least one JAR was scanned for TLDs yet contained no TLDs. Enable debug logging for this logger for a complete list of JARs that were scanned but no TLDs were found in them. Skipping unneeded JARs during scanning can improve startup time and JSP compilation time.
08:33:31,386 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback-test.xml]
08:33:31,386 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback.groovy]
08:33:31,386 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Found resource [logback.xml] at [file:/opt/tomcat/webapps/skos-play/WEB-INF/classes/logback.xml]
08:33:31,388 |-WARN in ch.qos.logback.classic.LoggerContext[default] - Resource [logback.xml] occurs multiple times on the classpath.
08:33:31,388 |-WARN in ch.qos.logback.classic.LoggerContext[default] - Resource [logback.xml] occurs at [file:/opt/tomcat/webapps/skos-play/WEB-INF/classes/logback.xml]
08:33:31,388 |-WARN in ch.qos.logback.classic.LoggerContext[default] - Resource [logback.xml] occurs at [jar:file:/opt/tomcat/webapps/skos-play/WEB-INF/lib/xls2rdf-lib-master-8bb3852c02-1.jar!/logback.xml]
08:33:31,448 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - debug attribute not set
08:33:31,450 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [ch.qos.logback.core.ConsoleAppender]
08:33:31,462 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [STDOUT]
08:33:31,470 |-INFO in ch.qos.logback.core.joran.action.NestedComplexPropertyIA - Assuming default type [ch.qos.logback.classic.encoder.PatternLayoutEncoder] for [encoder] property
08:33:31,512 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [ch.qos.logback.core.rolling.RollingFileAppender]
08:33:31,515 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [SKOSPLAY_ROLLING_FILE]
08:33:31,527 |-INFO in c.q.l.core.rolling.TimeBasedRollingPolicy@953996723 - No compression will be used
08:33:31,529 |-INFO in c.q.l.core.rolling.TimeBasedRollingPolicy@953996723 - Will use the pattern /opt/tomcat/logs/skos-play.%d{yyyy-MM-dd}.log for the active file
08:33:31,534 |-INFO in c.q.l.core.rolling.DefaultTimeBasedFileNamingAndTriggeringPolicy - The date pattern is 'yyyy-MM-dd' from file name pattern '/opt/tomcat/logs/skos-play.%d{yyyy-MM-dd}.log'.
08:33:31,534 |-INFO in c.q.l.core.rolling.DefaultTimeBasedFileNamingAndTriggeringPolicy - Roll-over at midnight.
08:33:31,535 |-INFO in c.q.l.core.rolling.DefaultTimeBasedFileNamingAndTriggeringPolicy - Setting initial period to Mon May 30 15:24:26 UTC 2022
08:33:31,538 |-INFO in ch.qos.logback.core.joran.action.NestedComplexPropertyIA - Assuming default type [ch.qos.logback.classic.encoder.PatternLayoutEncoder] for [encoder] property
08:33:31,542 |-INFO in ch.qos.logback.core.rolling.RollingFileAppender[SKOSPLAY_ROLLING_FILE] - Active log file name: /opt/tomcat/logs/skos-play.log
08:33:31,542 |-INFO in ch.qos.logback.core.rolling.RollingFileAppender[SKOSPLAY_ROLLING_FILE] - File property is set to [/opt/tomcat/logs/skos-play.log]
08:33:31,544 |-INFO in ch.qos.logback.classic.joran.action.LevelAction - org.springframework.core level set to INFO
08:33:31,544 |-INFO in ch.qos.logback.classic.joran.action.LevelAction - org.springframework.beans level set to INFO
08:33:31,544 |-INFO in ch.qos.logback.classic.joran.action.LevelAction - org.springframework.context level set to INFO
08:33:31,544 |-INFO in ch.qos.logback.classic.joran.action.LevelAction - org.springframework.web level set to INFO
08:33:31,544 |-INFO in ch.qos.logback.classic.joran.action.LevelAction - org.apache.fop level set to INFO
08:33:31,544 |-INFO in ch.qos.logback.classic.joran.action.LevelAction - org.eclipse.rdf4j level set to INFO
08:33:31,546 |-INFO in ch.qos.logback.classic.joran.action.LevelAction - org.apache.http.wire level set to INFO
08:33:31,546 |-INFO in ch.qos.logback.classic.joran.action.LevelAction - org.apache.http level set to INFO
08:33:31,546 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting additivity of logger [fr.sparna.rdf] to false
08:33:31,546 |-INFO in ch.qos.logback.classic.joran.action.LevelAction - fr.sparna.rdf level set to DEBUG
08:33:31,546 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [SKOSPLAY_ROLLING_FILE] to Logger[fr.sparna.rdf]
08:33:31,547 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [STDOUT] to Logger[fr.sparna.rdf]
08:33:31,547 |-INFO in ch.qos.logback.classic.joran.action.RootLoggerAction - Setting level of ROOT logger to DEBUG
08:33:31,547 |-INFO in ch.qos.logback.classic.joran.action.LevelAction - ROOT level set to DEBUG
08:33:31,547 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [STDOUT] to Logger[ROOT]
08:33:31,547 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - End of configuration.
08:33:31,548 |-INFO in ch.qos.logback.classic.joran.JoranConfigurator@1dd8c4ab - Registering current configuration as safe fallback point

31-May-2022 08:33:31.571 SEVERE [main] org.apache.catalina.core.StandardContext.startInternal One or more Filters failed to start. Full details will be found in the appropriate container log file
31-May-2022 08:33:31.571 SEVERE [main] org.apache.catalina.core.StandardContext.startInternal Context [/skos-play] startup failed due to previous errors
31-May-2022 08:33:31.591 INFO [main] org.apache.catalina.startup.HostConfig.deployWAR Deployment of web application archive [/opt/tomcat/webapps/skos-play.war] has finished in [6,330] ms
31-May-2022 08:33:31.592 INFO [main] org.apache.catalina.startup.HostConfig.deployDirectory Deploying web application directory [/opt/tomcat/webapps/ROOT]
31-May-2022 08:33:31.622 INFO [main] org.apache.catalina.startup.HostConfig.deployDirectory Deployment of web application directory [/opt/tomcat/webapps/ROOT] has finished in [30] ms
31-May-2022 08:33:31.622 INFO [main] org.apache.catalina.startup.HostConfig.deployDirectory Deploying web application directory [/opt/tomcat/webapps/docs]
31-May-2022 08:33:31.644 INFO [main] org.apache.catalina.startup.HostConfig.deployDirectory Deployment of web application directory [/opt/tomcat/webapps/docs] has finished in [22] ms
31-May-2022 08:33:31.644 INFO [main] org.apache.catalina.startup.HostConfig.deployDirectory Deploying web application directory [/opt/tomcat/webapps/examples]
31-May-2022 08:33:31.803 INFO [main] org.apache.catalina.startup.HostConfig.deployDirectory Deployment of web application directory [/opt/tomcat/webapps/examples] has finished in [159] ms
31-May-2022 08:33:31.803 INFO [main] org.apache.catalina.startup.HostConfig.deployDirectory Deploying web application directory [/opt/tomcat/webapps/host-manager]
31-May-2022 08:33:31.828 INFO [main] org.apache.catalina.startup.HostConfig.deployDirectory Deployment of web application directory [/opt/tomcat/webapps/host-manager] has finished in [25] ms
31-May-2022 08:33:31.828 INFO [main] org.apache.catalina.startup.HostConfig.deployDirectory Deploying web application directory [/opt/tomcat/webapps/manager]
31-May-2022 08:33:31.845 INFO [main] org.apache.catalina.startup.HostConfig.deployDirectory Deployment of web application directory [/opt/tomcat/webapps/manager] has finished in [17] ms
31-May-2022 08:33:31.854 INFO [main] org.apache.coyote.AbstractProtocol.start Starting ProtocolHandler ["http-nio-8085"]
31-May-2022 08:33:31.878 INFO [main] org.apache.catalina.startup.Catalina.start Server startup in [6688] milliseconds`

**Comment by scuffster** [comment]
no [ERROR] but there is: 31-May-2022 08:33:31.571 SEVERE [main] org.apache.catalina.core.StandardContext.startInternal Context [/skos-play]

**Comment by tfrancart** [comment]
> 31-May-2022 08:33:31.571 SEVERE [main] org.apache.catalina.core.StandardContext.startInternal One or more Filters failed to start. Full details will be found in the appropriate container log file

**Comment by scuffster** [comment]
31-May-2022 08:28:38.151 INFO [main] org.apache.catalina.core.ApplicationContext.log SessionListener: contextDestroyed()
31-May-2022 08:28:38.152 INFO [main] org.apache.catalina.core.ApplicationContext.log ContextListener: contextDestroyed()
31-May-2022 08:30:55.578 SEVERE [main] org.apache.catalina.core.StandardContext.filterStart Exception starting filter [sessionFilter]
	java.lang.ClassCastException: fr.sparna.rdf.skosplay.SessionFilter cannot be cast to jakarta.servlet.Filter
		at org.apache.catalina.core.ApplicationFilterConfig.getFilter(ApplicationFilterConfig.java:252)
		at org.apache.catalina.core.ApplicationFilterConfig.<init>(ApplicationFilterConfig.java:103)
		at org.apache.catalina.core.StandardContext.filterStart(StandardContext.java:4562)
		at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5205)
		at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
		at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:726)
		at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:698)
		at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:747)
		at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:1027)
		at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:2001)
		at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
		at java.util.concurrent.FutureTask.run(FutureTask.java:266)
		at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75)
		at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:112)
		at org.apache.catalina.startup.HostConfig.deployWARs(HostConfig.java:828)
		at org.apache.catalina.startup.HostConfig.deployApps(HostConfig.java:478)
		at org.apache.catalina.startup.HostConfig.start(HostConfig.java:1708)
		at org.apache.catalina.startup.HostConfig.lifecycleEvent(HostConfig.java:320)
		at org.apache.catalina.util.LifecycleBase.fireLifecycleEvent(LifecycleBase.java:123)
		at org.apache.catalina.util.LifecycleBase.setStateInternal(LifecycleBase.java:423)
		at org.apache.catalina.util.LifecycleBase.setState(LifecycleBase.java:366)
		at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:946)
		at org.apache.catalina.core.StandardHost.startInternal(StandardHost.java:886)
		at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
		at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1396)
		at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1386)
		at java.util.concurrent.FutureTask.run(FutureTask.java:266)
		at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75)
		at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:134)
		at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:919)
		at org.apache.catalina.core.StandardEngine.startInternal(StandardEngine.java:263)
		at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
		at org.apache.catalina.core.StandardService.startInternal(StandardService.java:432)
		at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
		at org.apache.catalina.core.StandardServer.startInternal(StandardServer.java:927)
		at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
		at org.apache.catalina.startup.Catalina.start(Catalina.java:795)
		at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
		at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
		at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
		at java.lang.reflect.Method.invoke(Method.java:498)
		at org.apache.catalina.startup.Bootstrap.start(Bootstrap.java:345)
		at org.apache.catalina.startup.Bootstrap.main(Bootstrap.java:476)
31-May-2022 08:30:55.840 INFO [main] org.apache.catalina.core.ApplicationContext.log ContextListener: contextInitialized()
31-May-2022 08:30:55.840 INFO [main] org.apache.catalina.core.ApplicationContext.log SessionListener: contextInitialized()
31-May-2022 08:30:55.841 INFO [main] org.apache.catalina.core.ApplicationContext.log ContextListener: attributeAdded('StockTicker', 'async.Stockticker@31c519de')
31-May-2022 08:32:48.038 INFO [main] org.apache.catalina.core.ApplicationContext.log SessionListener: contextDestroyed()
31-May-2022 08:32:48.038 INFO [main] org.apache.catalina.core.ApplicationContext.log ContextListener: contextDestroyed()
31-May-2022 08:33:31.571 SEVERE [main] org.apache.catalina.core.StandardContext.filterStart Exception starting filter [sessionFilter]
	java.lang.ClassCastException: fr.sparna.rdf.skosplay.SessionFilter cannot be cast to jakarta.servlet.Filter
		at org.apache.catalina.core.ApplicationFilterConfig.getFilter(ApplicationFilterConfig.java:252)
		at org.apache.catalina.core.ApplicationFilterConfig.<init>(ApplicationFilterConfig.java:103)
		at org.apache.catalina.core.StandardContext.filterStart(StandardContext.java:4562)
		at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5205)
		at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
		at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:726)
		at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:698)
		at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:747)
		at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:1027)
		at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:2001)
		at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
		at java.util.concurrent.FutureTask.run(FutureTask.java:266)
		at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75)
		at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:112)
		at org.apache.catalina.startup.HostConfig.deployWARs(HostConfig.java:828)
		at org.apache.catalina.startup.HostConfig.deployApps(HostConfig.java:478)
		at org.apache.catalina.startup.HostConfig.start(HostConfig.java:1708)
		at org.apache.catalina.startup.HostConfig.lifecycleEvent(HostConfig.java:320)
		at org.apache.catalina.util.LifecycleBase.fireLifecycleEvent(LifecycleBase.java:123)
		at org.apache.catalina.util.LifecycleBase.setStateInternal(LifecycleBase.java:423)
		at org.apache.catalina.util.LifecycleBase.setState(LifecycleBase.java:366)
		at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:946)
		at org.apache.catalina.core.StandardHost.startInternal(StandardHost.java:886)
		at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
		at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1396)
		at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1386)
		at java.util.concurrent.FutureTask.run(FutureTask.java:266)
		at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75)
		at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:134)
		at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:919)
		at org.apache.catalina.core.StandardEngine.startInternal(StandardEngine.java:263)
		at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
		at org.apache.catalina.core.StandardService.startInternal(StandardService.java:432)
		at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
		at org.apache.catalina.core.StandardServer.startInternal(StandardServer.java:927)
		at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
		at org.apache.catalina.startup.Catalina.start(Catalina.java:795)
		at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
		at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
		at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
		at java.lang.reflect.Method.invoke(Method.java:498)
		at org.apache.catalina.startup.Bootstrap.start(Bootstrap.java:345)
		at org.apache.catalina.startup.Bootstrap.main(Bootstrap.java:476)
31-May-2022 08:33:31.792 INFO [main] org.apache.catalina.core.ApplicationContext.log ContextListener: contextInitialized()
31-May-2022 08:33:31.793 INFO [main] org.apache.catalina.core.ApplicationContext.log SessionListener: contextInitialized()
31-May-2022 08:33:31.794 INFO [main] org.apache.catalina.core.ApplicationContext.log ContextListener: attributeAdded('StockTicker', 'async.Stockticker@13aa664a')

**Comment by scuffster** [comment]
that was the localhost.2022-05-31.log file
